### ISSUE TITLE
Interpolators crashing completely with input

### ISSUE THREAD

**Issue by Luadih** [OpenTabletDriver/TabletDriverFilters#14]
When trying to use AntiChatter or Smoothing (Both Interpolators) they crash OTD instantly when getting an input from the tablet.

Filter Values (Just in case)
![Filter Values (Just in case)](https://user-images.githubusercontent.com/50816896/105147680-4747e400-5ae0-11eb-8a88-0c245367359c.png)
After Input
![After Input](https://user-images.githubusercontent.com/50816896/105147349-d7d1f480-5adf-11eb-810d-3f53d011b020.png)

(Edit: Fixed description of the images. Sorry if i have any problems, first time opening an issue.)

Technical Data:
- Tablet: CTL-472
- OS: Windows 10 (64 Bits)
- Without having installed Wacom drivers

**Comment by X9VoiD** [comment]
This is already fixed on latest master. The release will come in sync with OTD 0.5.1 hotfix.
