### ISSUE TITLE
Devocub Antichatter breaks mouse clicks on XP-Pen G640s

### ISSUE THREAD

**Issue by Peasman** [OpenTabletDriver/TabletDriverFilters#23]
When using OpenTabletDriver 0.6.0.3 with the Devocub Antichatter every mouse click gets registered as two clicks (or more) on my XP-Pen G640s. Issue is said to be fixed [Discussion](https://github.com/OpenTabletDriver/OpenTabletDriver/discussions/1942) but even when building the newest version manually the issue persists. 

[diagnostics.txt](https://github.com/OpenTabletDriver/TabletDriverFilters/files/8007894/diagnostics.txt)

**Comment by wolkix3** [comment]
Still persisting in 0.6.0.4. It seems like the plugin causes the driver to disable the check for when dragging with the pen, since if dragging the pen, it just keeps on clicking continuously kind of like an auto clicker.

**Comment by jamesbt365** [comment]
Its actually resolved in the latest commit but @InfinityGhost has yet to actually push the release. Either compile a build yourself or give me a few minutes to compile it and i'll send a build here

**Comment by jamesbt365** [comment]
[DevoCubFilters.zip](https://github.com/OpenTabletDriver/TabletDriverFilters/files/9031431/DevoCubFilters.zip)

**Comment by wolkix3** [comment]
Thanks a lot, literally just saw the changes after posting this. Mb for not checking first

**Comment by X9VoiD** [comment]
Closing this as it's actually already been resolved in master but just forgot to close.
